"""delete uuid column in users table

Revision ID: d4cb107787da
Revises: 849565623da2
Create Date: 2024-12-23 20:10:18.017851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cb107787da'
down_revision: Union[str, None] = '849565623da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_uuid_key', 'users', type_='unique')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_uuid_key', 'users', ['uuid'])
    # ### end Alembic commands ###
