"""create product model

Revision ID: be67d3e44dbd
Revises: e84e0ae897cf
Create Date: 2025-03-26 13:42:12.257354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be67d3e44dbd'
down_revision: Union[str, None] = 'e84e0ae897cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo')
    # ### end Alembic commands ###
